name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate"
dev = "node enable-embed.js && npx prisma migrate deploy && npm exec react-router dev"
