# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a892f96d98d55d99fa52c6e7137e57bd"
name = "nydhi-loyalty"
application_url = "https://sold-surgeons-chart-barry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sold-surgeons-chart-barry.trycloudflare.com/auth/callback",
  "https://sold-surgeons-chart-barry.trycloudflare.com/api/auth",
  "https://sold-surgeons-chart-barry.trycloudflare.com/auth/shopify/callback"
]
